name: Crete new git Ref
description: Crete new git Ref from another Ref
inputs:
  from_ref:
    description: git ref wrom which one we will create new ref
    required: true
  to_ref:
    description: git ref wrom which one we will create new ref
    required: true
  github-token:
    description: GitHub token with write access to repo
    required: true
runs:
  using: composite
  steps:
    - uses: actions/github-script@v5
      name: Set version
      id: version
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const owner = context.repo.owner
          const repo = context.repo.repo
          const ref = await github.rest.git.getRef({owner, repo, ref: '${{ inputs.from_ref }}' })
          const result =  await github.rest.git.createRef({ owner, repo, ref: 'refs/${{ inputs.to_ref }}', sha: ref.data.object.sha })
          console.log('result',result.data)
